---
# tasks file for roles/database
  - name: Launch Database
    docker_container:
      name: tp1-postgres-server
      image: niryantso/tp1-postgres-server:4.0
      state: started
      networks:
        - name: "app-network"
      env:
        POSTGRES_USER: "usr"
        POSTGRES_PASSWORD: "pwd"
        POSTGRES_DB: "db"