version: '3.7'

services:
  bck:
    build: ./api
    networks:
      - app-network
    depends_on:
      - postgres-server

  postgres-server: 
    build: ./postgres
    networks:
      - app-network
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  apache: 
    build: ./http-server
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - bck

  front:
    build: ./front
    depends_on:
      - apache
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    external: true

